from pathlib import Path

from Bugfix_agent.agent.state import AgentState, BugReport
from Bugfix_agent.agent.workflow import workflow as bug_fix_workflow
from Bugfix_agent.retrieval.state import IndexingState
from Bugfix_agent.retrieval.workflow import workflow as retrieval_workflow

_INDEX_FILE = "repo.index"
_METADATA_FILE = "paths.pkl"

class RepositoryNotIndexedError(Exception):
    """Raised when fix_bug() is called before index_repository()."""


class BugFixAgent:
    """Simple orchestrator exposing the public API of the package."""

    def index_repository(self, repo_path: str):
        """
        Runs the retrieval workflow and creates all required indexing
        artifacts (FAISS index, metadata, etc.) for ``repo_path``.
        """
        initial_state: IndexingState = {
            "repo_path": repo_path,
        }

        return retrieval_workflow.invoke(initial_state)

    def fix_bug(self, repo_path: str, bug_report: str):
        """
        Runs the bug-fixing workflow for ``bug_report`` using the index
        previously generated by ``index_repository(repo_path)``.
        """
        self._ensure_indexed()

        initial_state: AgentState = {
            "bug_report": BugReport(
                bug_report=bug_report,
                bug_report_embedding=[],
            ),
            "repo_path": repo_path,
            "retry_count": 0,
            "repair_history": [],
        }

        return bug_fix_workflow.invoke(initial_state)

    def _ensure_indexed(self):
        missing = [
            name
            for name in (_INDEX_FILE, _METADATA_FILE)
            if not Path(name).exists()
        ]

        if missing:
            raise RepositoryNotIndexedError(
                "Repository has not been indexed.\n"
                "Run index_repository(repo_path) first."
            )
