from pathlib import Path

from Bugfix_agent.agent.state import AgentState, BugReport
from Bugfix_agent.agent.workflow import workflow as bug_fix_workflow
from Bugfix_agent.retrieval.state import IndexingState
from Bugfix_agent.retrieval.workflow import workflow as retrieval_workflow

_BUGFIX_DIR= ".bugfix"
_INDEX_FILE = "repo.index"
_METADATA_FILE = "paths.pkl"

class BugFixAgentPath:
    def __init__(self, repo_path: str):
        self.repo_path = repo_path
    
    def get_index_file_path(self) -> Path:
        return Path(self.repo_path) / _BUGFIX_DIR / _INDEX_FILE
    
    def get_metadata_file_path(self) -> Path:
        return Path(self.repo_path) / _BUGFIX_DIR / _METADATA_FILE
    
    def get_bugfix_dir_path(self) -> Path:
        return Path(self.repo_path) / _BUGFIX_DIR

class RepositoryNotIndexedError(Exception):
    """Raised when fix_bug() is called before index_repository()."""


class BugFixAgent:
    """orchestrator exposing the public API of the package."""
    def __init__(self, repo_path: str):
        self.repo_path = repo_path
        self.path_handler = BugFixAgentPath(repo_path)
        
    def _ensure_git_ignore(self):
        """
        Ensures that the .bugfix directory is ignored by git.
        """
        gitignore = Path(self.repo_path) / ".gitignore"

        if not gitignore.exists():
            gitignore.write_text(f"{_BUGFIX_DIR}/\n", encoding="utf-8")
            return

        contents = gitignore.read_text(encoding="utf-8")

        if f"{_BUGFIX_DIR}/" in contents:
            return

        if contents and not contents.endswith("\n"):
            contents += "\n"

        contents += f"{_BUGFIX_DIR}/\n"

        gitignore.write_text(contents, encoding="utf-8")

    def index_repository(self):
        """
        Runs the retrieval workflow and creates all required indexing
        artifacts (FAISS index, metadata, etc.) for ``repo_path``.
        """
        self.path_handler.get_bugfix_dir_path().mkdir(
            parents=True,
            exist_ok=True
        )
        self._ensure_git_ignore()
        initial_state: IndexingState = {
            "repo_path": self.repo_path,
            "index_path": str(self.path_handler.get_index_file_path()),
            "metadata_file_path": str(self.path_handler.get_metadata_file_path())
        }

        return retrieval_workflow.invoke(initial_state)

    def fix_bug(self, bug_report: str):
        """
        Runs the bug-fixing workflow for ``bug_report`` using the index
        previously generated by ``index_repository()``.
        """
        self._ensure_indexed()

        initial_state: AgentState = {
            "bug_report": BugReport(
                bug_report=bug_report,
                bug_report_embedding=[],
            ),
            "repo_path": self.repo_path,
            "retry_count": 0,
            "repair_history": [],
            "index_path": str(self.path_handler.get_index_file_path()),
            "metadata_file_path": str(self.path_handler.get_metadata_file_path())
        }

        return bug_fix_workflow.invoke(initial_state)

    def _ensure_indexed(self):
        missing = []
        
        if not self.path_handler.get_bugfix_dir_path().exists():
            missing.append(self.path_handler.get_bugfix_dir_path())
            
        if not self.path_handler.get_index_file_path().exists():
            missing.append(self.path_handler.get_index_file_path())
            
        if not self.path_handler.get_metadata_file_path().exists():
            missing.append(self.path_handler.get_metadata_file_path())

        if missing:
            raise RepositoryNotIndexedError(
                "Repository has not been indexed.\n"
                "Run index_repository() first."
            )
